spring:
    application:
        name: music-service
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: qwerty
        driver-class-name: org.postgresql.Driver
    servlet:
        multipart:
            max-file-size: 20MB

aws:
    s3:
        endpoint: https://s3.twcstorage.ru
        region: ru-1
        access-key: ${S3_ACCESS_KEY:}
        secret-key: ${S3_SECRET_KEY:}
        bucket: ${S3_BUCKET:}
        public-url-prefix: https://s3.twcstorage.ru/dff2fb2a-f4c1-4ba0-a0ef-42aab0ae6870

jwt:
    secret: ${JWT_SECRET:}
    access-expiration: 900000
    refresh-expiration: 604800000

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method