INSERT INTO users (username, avatar, password, is_artist, email) VALUES
    ('Cutting Crew - Topic', NULL, 'test123', TRUE, 'cutting_crew_topic@example.com'),
    ('a-ha', NULL, 'test123', TRUE, 'a_ha@example.com'),
    ('Alphaville', NULL, 'test123', TRUE, 'alphaville@example.com'),
    ('Modern Talking', NULL, 'test123', TRUE, 'modern_talking@example.com'),
    ('Boney M.', NULL, 'test123', TRUE, 'boney_m@example.com'),
    ('ABBA - Topic', NULL, 'test123', TRUE, 'abba_topic@example.com'),
    ('Various Artists - Topic', NULL, 'test123', TRUE, 'various_artists_topic@example.com'),
    ('C.C. Catch', NULL, 'test123', TRUE, 'cc_catch@example.com'),
    ('Sandra - Topic', NULL, 'test123', TRUE, 'sandra_topic@example.com'),
    ('Pet Shop Boys - Topic', NULL, 'test123', TRUE, 'pet_shop_boys_topic@example.com'),
    ('Madonna', NULL, 'test123', TRUE, 'madonna@example.com'),
    ('Roxette', NULL, 'test123', TRUE, 'roxette@example.com'),
    ('Madonna - Topic', NULL, 'test123', TRUE, 'madonna_topic@example.com'),
    ('Cliff Turner', NULL, 'test123', TRUE, 'cliff_turner@example.com'),
    ('Rick Astley', NULL, 'test123', TRUE, 'rick_astley@example.com'),
    ('Sabrina', NULL, 'test123', TRUE, 'sabrina@example.com'),
    ('Bee Gees - Topic', NULL, 'test123', TRUE, 'bee_gees_topic@example.com'),
    ('DESIRELESS', NULL, 'test123', TRUE, 'desireless@example.com'),

    ('ANDROMEDA & elysian.', NULL, 'test123', TRUE, 'andromeda_elysian@example.com'),
    ('DVRST, Valerii Zaitsev', NULL, 'test123', TRUE, 'dvrst_valerii_zaitsev@example.com'),
    ('DJZRX', NULL, 'test123', TRUE, 'djzrx@example.com'),
    ('PXLWYSE', NULL, 'test123', TRUE, 'pxlwyse@example.com'),
    ('Ogryzek', NULL, 'test123', TRUE, 'ogryzek@example.com'),
    ('HISTED & TXVSTERPLAYA', NULL, 'test123', TRUE, 'histed_txvsterplaya@example.com'),
    ('Hwungii', NULL, 'test123', TRUE, 'hwungii@example.com'),
    ('INTERWORLD', NULL, 'test123', TRUE, 'interworld@example.com'),
    ('KHAOS', NULL, 'test123', TRUE, 'khaos@example.com'),
    ('LXNGVX', NULL, 'test123', TRUE, 'lxngvx@example.com'),
    ('Kordhell, Mick Kenney', NULL, 'test123', TRUE, 'kordhell_mick_kenney@example.com'),
    ('MXZI', NULL, 'test123', TRUE, 'mxzi@example.com'),
    ('NCTS', NULL, 'test123', TRUE, 'ncts@example.com'),
    ('Eternxlkz', NULL, 'test123', TRUE, 'eternxlkz@example.com'),
    ('L.P. Rhythm', NULL, 'test123', TRUE, 'lp_rhythm@example.com'),
    ('ZXKAI', NULL, 'test123', TRUE, 'zxkai@example.com');